version: "3"
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "5555:80"
    volumes:
      - ./pg_admin_data:/root/.pgadmin
    env_file:
      - docker.env
    depends_on:
      - postgres

  nestjs-api:
    image: flippy28/barker_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
